[tool.poetry]
name = "replaybuffer"
version = "0.1.0"
description = ""
authors = ["Artem <a4b11s@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
